# Day 3: Gear Ratios

## Part One

You and the Elf eventually reach a gondola lift station; he says the gondola lift will take you up to the water source, but this is as far as he can bring you. You go inside.

It doesn't take long to find the gondolas, but there seems to be a problem: they're not moving.

"Aaah!"

You turn around to see a slightly-greasy Elf with a wrench and a look of surprise. "Sorry, I wasn't expecting anyone! The gondola lift isn't working right now; it'll still be a while before I can fix it." You offer to help.

The engineer explains that an engine part seems to be missing from the engine, but nobody can figure out which one. If you can add up all the part numbers in the engine schematic, it should be easy to work out which part is missing.

The engine schematic (your puzzle input) consists of a visual representation of the engine. There are lots of numbers and symbols you don't really understand, but apparently any number adjacent to a symbol, even diagonally, is a "part number" and should be included in your sum. (Periods (.) do not count as a symbol.)

Here is an example engine schematic:

In [10]:
example = [
    "467..114..",
    "...*......",
    "..35..633.",
    "......#...",
    "617*......",
    ".....+.58.",
    "..592.....",
    "......755.",
    "...\$.*....",
    ".664.598.."
]

10-element Vector{String}:
 "467..114.."
 "...*......"
 "..35..633."
 "......#..."
 "617*......"
 ".....+.58."
 "..592....."
 "......755."
 "...\$.*...."
 ".664.598.."

In this schematic, two numbers are not part numbers because they are not adjacent to a symbol: 114 (top right) and 58 (middle right). Every other number is adjacent to a symbol and so is a part number; their sum is 4361.

Of course, the actual engine schematic is much larger. What is the sum of all of the part numbers in the engine schematic?



In [11]:
function findnumber(ln, start)
    for i in start:lastindex(ln)
        if isdigit(ln[i])
            for j in i:lastindex(ln)
                if isdigit(ln[j])
                    continue
                end
                return (i:j-1, parse(Int, ln[i:j-1]))
            end
            return (i:lastindex(ln), parse(Int, ln[i:end]))
        end
    end
    nothing
end

function findnumbers(contents)
    numbers = []
    for y in firstindex(contents):lastindex(contents)
        searchindex = firstindex(contents[y])
        r = findnumber(contents[y], searchindex)
        while r !== nothing
            (xrange, value) = r
            searchindex = xrange.stop + 1
            push!(numbers, (y, xrange, value))
            r = findnumber(contents[y], searchindex)
        end
    end
    return numbers
end

function isajacenttosymbol(val, contents)
    (y, xrange) = val
    for yidx in max(firstindex(contents), y - 1):min(lastindex(contents), y + 1)
        for xidx in max(firstindex(contents[yidx]), xrange.start - 1):min(lastindex(contents[yidx]), xrange.stop + 1)
            if isdigit(contents[yidx][xidx])
                continue
            elseif contents[yidx][xidx] == '.'
                continue
            else
                return true
            end
        end
    end
    return false
end

function partone(contents)
    parts = findnumbers(contents)
    sum(map(x -> x[3], filter(val -> isajacenttosymbol(val, contents), parts)))
end

partone(example)

4361

## Part Two

The engineer finds the missing part and installs it in the engine! As the engine springs to life, you jump in the closest gondola, finally ready to ascend to the water source.

You don't seem to be going very fast, though. Maybe something is still wrong? Fortunately, the gondola has a phone labeled "help", so you pick it up and the engineer answers.

Before you can explain the situation, she suggests that you look out the window. There stands the engineer, holding a phone in one hand and waving with the other. You're going so slowly that you haven't even left the station. You exit the gondola.

The missing part wasn't the only issue - one of the gears in the engine is wrong. A gear is any * symbol that is adjacent to exactly two part numbers. Its gear ratio is the result of multiplying those two numbers together.

This time, you need to find the gear ratio of every gear and add them all up so that the engineer can figure out which gear needs to be replaced.

Consider the same engine schematic again:

In [12]:
example

10-element Vector{String}:
 "467..114.."
 "...*......"
 "..35..633."
 "......#..."
 "617*......"
 ".....+.58."
 "..592....."
 "......755."
 "...\$.*...."
 ".664.598.."


In this schematic, there are two gears. The first is in the top left; it has part numbers 467 and 35, so its gear ratio is 16345. The second gear is in the lower right; its gear ratio is 451490. (The * adjacent to 617 is not a gear because it is only adjacent to one part number.) Adding up all of the gear ratios produces 467835.

What is the sum of all of the gear ratios in your engine schematic?



In [13]:
function findgears(contents)
    [(y, x) for y in firstindex(contents):lastindex(contents) for x in firstindex(contents[y]):lastindex(contents[y]) if contents[y][x] === '*']
end

function gearratios(gear, parts)
    (y, x) = gear
    adj = []
    for (yidx, xrange, partnum) in parts
        if yidx == y - 1 || yidx == y || yidx == y + 1
            if x - 1 in xrange || x in xrange || x + 1 in xrange
                push!(adj, partnum)
            end
        end
    end
    if length(adj) == 2
        return prod(adj)
    end
    return 0
end

function parttwo(contents)
    parts = findnumbers(contents)
    gears = findgears(contents)
    sum(map(gear -> gearratios(gear, parts), gears))
end

parttwo(example)

467835

# Results

In [14]:
include("./aoc.jl")
execute(3, partone, parttwo)

527364
79026871
